<!DOCTYPE html>
<html lang="id">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{{ $title }} | Pondokan Tamara</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body class="admin-page">
    <header class="admin-header"><a class="brand" href="{{ route('admin.rooms.index') }}"><span class="brand-mark" aria-hidden="true"></span><span><strong>Pondokan</strong><small>Tamara admin</small></span></a><a class="text-link" href="{{ route('admin.rooms.index') }}">Kembali ke daftar</a></header>
    <main class="admin-content admin-form-page"><p class="eyebrow">Kelola kamar</p><h1>{{ $title }}</h1>
        @if($errors->any())<div class="form-error">{{ $errors->first() }}</div>@endif
        <form method="POST" action="{{ route('admin.rooms.update', $room) }}" class="admin-form room-form">@csrf @method('PUT')
            <div class="form-grid"><label>Lokasi<select name="location_key" id="adminLocation" required><option value="tamara-1" @selected(old('location_key', $room->location_key ?? '') === 'tamara-1')>Pondokan Tamara I</option><option value="tamara-2" @selected(old('location_key', $room->location_key ?? '') === 'tamara-2')>Pondokan Tamara II</option></select></label><label>Nomor kamar<input name="code" value="{{ old('code', $room->code) }}" placeholder="A-01" required></label><label>Tipe kamar<select name="type" required>@foreach(['Standard', 'Comfort', 'VIP'] as $type)<option value="{{ $type }}" @selected(old('type', $room->type) === $type)>{{ $type }}</option>@endforeach</select></label><label>Ukuran kamar<input name="size" value="{{ old('size', $room->size) }}" placeholder="4 x 4 m" required></label><label>Harga per bulan<input type="number" name="price" value="{{ old('price', $room->price) }}" min="0" required></label><label>Status<select name="status" required>@foreach(['available' => 'Tersedia', 'occupied' => 'Terisi', 'reserved' => 'Dipesan'] as $value => $label)<option value="{{ $value }}" @selected(old('status', $room->status ?: 'available') === $value)>{{ $label }}</option>@endforeach</select></label></div>
            @php($roomsByPosition = $rooms->keyBy('position'))
            @php($displayPositions = ['Lantai 1' => [1 => 23, 2 => 22, 3 => 14, 4 => 1, 5 => 21, 6 => 20, 7 => 15, 8 => 2, 9 => 16, 10 => 3, 12 => 4, 13 => 5, 14 => 6], 'Lantai 2' => [1 => 27, 2 => 26, 3 => 17, 4 => 7, 5 => 25, 6 => 24, 7 => 18, 8 => 8, 9 => 19, 10 => 9, 12 => 10, 13 => 11, 14 => 12]])
            <section class="position-editor"><div class="position-editor-heading"><div><p class="eyebrow">Denah kamar</p><h2>Pindah ke kamar lain.</h2></div><p>Klik posisi untuk membuka kamar yang menempati posisi tersebut.</p></div><div class="room-map admin-position-map layout-tamara-1 floor-{{ $room->floor === 'Lantai 2' ? 'two' : 'one' }}"><div class="layout-label label-kitchen">DAPUR</div><div class="layout-label label-laundry">JEMURAN</div><div class="layout-label label-bathroom">KAMAR MANDI</div><div class="layout-label label-bathroom-mid">KAMAR MANDI</div><div class="layout-label label-parking">{{ $room->floor === 'Lantai 1' ? 'PARKIRAN' : 'NONGKRONG' }}</div><div class="layout-label label-bathroom-laundry">KAMAR MANDI &amp; JEMURAN</div><div class="layout-label label-owner">RUMAH PEMILIK KOS</div>@for($position = 1; $position <= $rooms->count(); $position++) @php($positionRoom = $roomsByPosition->get($position)) @if($positionRoom) @if($positionRoom->code === 'Rumah penjaga kos')<div class="room-tile position-tile special-position-tile position-11-label">Rumah penjaga kos</div>@else<a class="room-tile position-tile {{ $positionRoom->status }} {{ $positionRoom->id === $room->id ? 'position-selected' : '' }}" data-position="{{ $position }}" href="{{ route('admin.rooms.edit', $positionRoom) }}" title="Edit posisi {{ $position }}">{{ $positionRoom->code === 'VIP' ? 'VIP' : ($displayPositions[$room->floor][$position] ?? $position) }}</a>@endif @endif @endfor</div></section>
            <fieldset><legend>Fasilitas kamar</legend><div class="facility-grid">@php($selected = old('features', $room->features ?? [])) @foreach(['Tempat tidur biasa', 'Tempat tidur springbed', 'Lemari', 'Kursi', 'Meja', 'TV', 'Kamar mandi dalam', 'Kamar mandi luar', 'WC duduk', 'Shower', 'Meja Rias', 'Ruang tamu'] as $feature)<label class="check-row"><input type="checkbox" name="features[]" value="{{ $feature }}" @checked(in_array($feature, $selected, true))>{{ $feature }}</label>@endforeach</div></fieldset>
            <button class="button button-dark admin-submit" type="submit">Simpan kamar <span>↗</span></button>
        </form>
    </main>
</body>
</html>
